version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: monthly
      time: "00:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 1
    assignees:
      - marcel-breuer
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
